In [1]:
import pandas, warnings

warnings.filterwarnings('ignore')

In [2]:
filmurl = '/content/ml-latest/movies.csv'

In [3]:
film = pandas.read_table(filmurl, sep = ',')

film.iloc[:5]

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [4]:
film.tail()

,movieId,title,genres
86532,288967,State of Siege: Temple Attack (2021),Action|Drama
86533,288971,Ouija Japan (2021),Action|Horror
86534,288975,The Men Who Made the Movies: Howard Hawks (1973),Documentary
86535,288977,Skinford: Death Sentence (2023),Crime|Thriller
86536,288983,UNZIPPED: An Autopsy of American Inequality (2...,Documentary

In [5]:
film.isnull().sum().sum()

np.int64(0)

In [6]:
tagsurl = '/content/ml-latest/tags.csv'

tags = pandas.read_table(tagsurl, sep = ',')

tags.iloc[:5]

   userId  movieId            tag   timestamp
0      10      260   good vs evil  1430666558
1      10      260  Harrison Ford  1430666505
2      10      260         sci-fi  1430666538
3      14     1221      Al Pacino  1311600756
4      14     1221          mafia  1311600746

In [7]:
tags.tail()

         userId  movieId                  tag   timestamp
2328310  330923   176599  politically correct  1507547491
2328311  330933     3317        coming of age  1351279384
2328312  330933     3317            sexuality  1351279389
2328313  330947     5782       Not Luc Besson  1154110902
2328314  330947    44191           comic book  1154271525

In [8]:
gescore = '/content/ml-latest/genome-scores.csv'

gescoretable = pandas.read_table(gescore, sep = ',')

gescoretable.iloc[:5]

   movieId  tagId  relevance
0        1      1    0.03200
1        1      2    0.02225
2        1      3    0.07000
3        1      4    0.05900
4        1      5    0.12300

In [9]:
gescoretable.tail()

          movieId  tagId  relevance
18472123   288167   1124    0.09875
18472124   288167   1125    0.02950
18472125   288167   1126    0.02275
18472126   288167   1127    0.11225
18472127   288167   1128    0.03025

In [10]:
getags = '/content/ml-latest/genome-tags.csv'

getagstable = pandas.read_table(getags, sep = ',')

getagstable.iloc[:5]

   tagId           tag
0      1           007
1      2  007 (series)
2      3  18th century
3      4         1920s
4      5         1930s

In [11]:
getagstable.tail()

      tagId      tag
1123   1124  writing
1124   1125    wuxia
1125   1126     wwii
1126   1127   zombie
1127   1128  zombies